# Generated by Django 4.0.5 on 2022-06-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newusers',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
