# Generated by Django 4.0.5 on 2022-06-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_rename_phone_newusers_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newusers',
            name='phone_no',
        ),
    ]
